FROM quay.io/podman/stable:latest

RUN set -e && \
  dnf update -y && \
  dnf clean all

COPY --chown=1000:1000 entrypoint.sh /
COPY --chown=1000:1000 workspace-recovery.sh /

RUN chmod +x /entrypoint.sh ; \
  chmod +x /workspace-recovery.sh

ENTRYPOINT ["/entrypoint.sh"]
