// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sync

import (
	"context"
	"errors"
	"reflect"
	"testing"

	"github.com/go-logr/logr"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/utils/ptr"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	"github.com/devfile/devworkspace-operator/pkg/constants"
)

// Generated by Codex
func TestSyncDiscoverableServicePreservesForeignService(t *testing.T) {
	for _, scenario := range []string{"hidden by cache", "created after precheck", "matching label with foreign owner", "created during synchronization"} {
		t.Run(scenario, func(t *testing.T) {
			ctx := context.Background()
			scheme := runtime.NewScheme()
			if err := corev1.AddToScheme(scheme); err != nil {
				t.Fatal(err)
			}
			foreign := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "ns", UID: "foreign-service"}, Spec: corev1.ServiceSpec{Selector: map[string]string{"app": "foreign"}, Ports: []corev1.ServicePort{{Port: 8080}}}}
			desired := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "ns", Labels: map[string]string{constants.DevWorkspaceIDLabel: "mine"}, Annotations: map[string]string{constants.DevWorkspaceDiscoverableServiceAnnotation: "true"}, OwnerReferences: []metav1.OwnerReference{{APIVersion: "controller.devfile.io/v1alpha1", Kind: "DevWorkspaceRouting", Name: "routing-mine", UID: "mine-routing", Controller: ptr.To(true)}}}, Spec: corev1.ServiceSpec{Selector: map[string]string{"app": "mine"}, Ports: []corev1.ServicePort{{Port: 8080}}}}
			if scenario != "hidden by cache" {
				foreign.Labels = map[string]string{constants.DevWorkspaceIDLabel: "other"}
			}
			if scenario == "matching label with foreign owner" {
				foreign.Labels[constants.DevWorkspaceIDLabel] = "mine"
				foreign.OwnerReferences = []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "other-routing", Controller: ptr.To(true)}}
			}
			backing := fake.NewClientBuilder().WithScheme(scheme).Build()
			var cached client.Client = backing
			if scenario == "hidden by cache" {
				cached = filteredServiceClient{backing}
			}
			api := ClusterAPI{Client: cached, NonCachingClient: backing, Ctx: ctx, Logger: logr.Discard()}
			if scenario == "created during synchronization" {
				api.Client = serviceCreateRaceClient{Client: backing, foreign: foreign}
			} else if err := backing.Create(ctx, foreign); err != nil {
				t.Fatal(err)
			}
			_, syncErr := SyncObjectWithCluster(desired, api)
			if syncErr == nil {
				t.Fatal("expected conflict or retry")
			}
			actual := &corev1.Service{}
			if err := backing.Get(ctx, client.ObjectKeyFromObject(foreign), actual); err != nil {
				t.Fatalf("foreign Service deleted: %v", err)
			}
			if !reflect.DeepEqual(actual.Spec, foreign.Spec) || !reflect.DeepEqual(actual.Labels, foreign.Labels) || !reflect.DeepEqual(actual.OwnerReferences, foreign.OwnerReferences) {
				t.Fatalf("foreign Service modified: %#v", actual)
			}
			if scenario == "created during synchronization" {
				var retry *NotInSyncError
				if !errors.As(syncErr, &retry) || retry.Reason != NeedRetryReason {
					t.Fatalf("want retry on create race, got %v", syncErr)
				}
				_, syncErr = SyncObjectWithCluster(desired, api)
			}
			var fatal *UnrecoverableSyncError
			if !errors.As(syncErr, &fatal) {
				t.Fatalf("want permanent Service conflict, got %v", syncErr)
			}
		})
	}
}

// Generated by Codex
func TestSyncDiscoverableServiceUpdatesOwnedService(t *testing.T) {
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	existing := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "ns", UID: "owned-service", Labels: map[string]string{constants.DevWorkspaceIDLabel: "mine"}, OwnerReferences: []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "mine-routing", Controller: ptr.To(true)}}}, Spec: corev1.ServiceSpec{ClusterIP: "10.0.0.1", Selector: map[string]string{"app": "old"}}}
	desired := existing.DeepCopy()
	desired.Annotations = map[string]string{constants.DevWorkspaceDiscoverableServiceAnnotation: "true"}
	desired.Spec.ClusterIP = ""
	desired.Spec.Selector = map[string]string{"app": "mine"}
	cl := fake.NewClientBuilder().WithScheme(scheme).WithObjects(existing).Build()
	_, err := SyncObjectWithCluster(desired, ClusterAPI{Client: cl, NonCachingClient: cl, Ctx: context.Background(), Logger: logr.Discard()})
	var pending *NotInSyncError
	if !errors.As(err, &pending) {
		t.Fatalf("want pending update, got %v", err)
	}
	actual := &corev1.Service{}
	if err := cl.Get(context.Background(), client.ObjectKeyFromObject(existing), actual); err != nil {
		t.Fatal(err)
	}
	if actual.Spec.Selector["app"] != "mine" || actual.Spec.ClusterIP != "10.0.0.1" || actual.UID != "owned-service" {
		t.Fatalf("owned Service was not updated in place: %#v", actual)
	}
}

// Generated by Codex
func TestSyncOwnedServiceRestoresMissingWorkspaceLabel(t *testing.T) {
	for _, discoverable := range []bool{false, true} {
		t.Run(map[bool]string{false: "aggregate", true: "discoverable"}[discoverable], func(t *testing.T) {
			ctx := context.Background()
			scheme := runtime.NewScheme()
			if err := corev1.AddToScheme(scheme); err != nil {
				t.Fatal(err)
			}
			existing := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "ns", UID: "owned-service", OwnerReferences: []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "mine-routing", Controller: ptr.To(true)}}}, Spec: corev1.ServiceSpec{ClusterIP: "10.0.0.1", Selector: map[string]string{"app": "old"}}}
			desired := existing.DeepCopy()
			desired.UID = ""
			desired.Labels = map[string]string{constants.DevWorkspaceIDLabel: "mine"}
			desired.Spec.ClusterIP = ""
			desired.Spec.Selector = map[string]string{"app": "mine"}
			if discoverable {
				desired.Annotations = map[string]string{constants.DevWorkspaceDiscoverableServiceAnnotation: "true"}
			}
			backing := fake.NewClientBuilder().WithScheme(scheme).WithObjects(existing).Build()
			api := ClusterAPI{Client: filteredServiceClient{backing}, NonCachingClient: backing, Ctx: ctx, Logger: logr.Discard()}
			_, err := SyncObjectWithCluster(desired, api)
			var pending *NotInSyncError
			if !errors.As(err, &pending) || pending.Reason != UpdatedObjectReason {
				t.Fatalf("want in-place update, got %v", err)
			}
			actual := &corev1.Service{}
			if err := backing.Get(ctx, client.ObjectKeyFromObject(existing), actual); err != nil {
				t.Fatal(err)
			}
			if actual.Labels[constants.DevWorkspaceIDLabel] != "mine" || actual.Spec.Selector["app"] != "mine" || actual.Spec.ClusterIP != "10.0.0.1" || actual.UID != "owned-service" {
				t.Fatalf("owned Service was not repaired in place: label=%q selector=%q clusterIP=%q uid=%q", actual.Labels[constants.DevWorkspaceIDLabel], actual.Spec.Selector["app"], actual.Spec.ClusterIP, actual.UID)
			}
		})
	}
}

// Generated by Codex
func TestSyncAggregateServiceRejectsHiddenForeignService(t *testing.T) {
	ctx := context.Background()
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	foreign := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "mine-service", Namespace: "ns", UID: "foreign-service"}, Spec: corev1.ServiceSpec{Selector: map[string]string{"app": "foreign"}}}
	desired := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "mine-service", Namespace: "ns", Labels: map[string]string{constants.DevWorkspaceIDLabel: "mine"}, OwnerReferences: []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "mine-routing", Controller: ptr.To(true)}}}, Spec: corev1.ServiceSpec{Selector: map[string]string{"app": "mine"}}}
	backing := fake.NewClientBuilder().WithScheme(scheme).WithObjects(foreign).Build()
	api := ClusterAPI{Client: filteredServiceClient{backing}, NonCachingClient: backing, Ctx: ctx, Logger: logr.Discard()}
	_, err := SyncObjectWithCluster(desired, api)
	var fatal *UnrecoverableSyncError
	var conflict *ServiceConflictError
	if !errors.As(err, &fatal) || !errors.As(err, &conflict) {
		t.Fatalf("want typed permanent conflict, got %v", err)
	}
	actual := &corev1.Service{}
	if err := backing.Get(ctx, client.ObjectKeyFromObject(foreign), actual); err != nil {
		t.Fatalf("foreign Service deleted: %v", err)
	}
	if actual.UID != "foreign-service" || actual.Spec.Selector["app"] != "foreign" || len(actual.Labels) != 0 {
		t.Fatalf("foreign Service modified: %#v", actual)
	}
}

// Generated by Codex
// filteredServiceClient models the production cache's workspace-label filter.
type filteredServiceClient struct{ client.Client }

func (c filteredServiceClient) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	if err := c.Client.Get(ctx, key, obj, opts...); err != nil {
		return err
	}
	_, labeled := obj.GetLabels()[constants.DevWorkspaceIDLabel]
	if _, ok := obj.(*corev1.Service); ok && !labeled {
		return apierrors.NewNotFound(schema.GroupResource{Resource: "services"}, key.Name)
	}
	return nil
}

// Generated by Codex
type serviceCreateRaceClient struct {
	client.Client
	foreign *corev1.Service
}

func (c serviceCreateRaceClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
	if err := c.Client.Create(ctx, c.foreign); err != nil {
		return err
	}
	return c.Client.Create(ctx, obj, opts...)
}
