//
// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package common

import (
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSanitizeVolumeName(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "replaces dots with hyphens",
			input:    "test.pullsecret",
			expected: "test-pullsecret",
		},
		{
			name:     "replaces all invalid characters and lowercases",
			input:    "Test.Secret_Name@example",
			expected: "test-secret-name-example",
		},
		{
			name:     "collapses consecutive invalid characters and trims edges",
			input:    ".test...secret.",
			expected: "test-secret",
		},
		{
			// Hyphens are non-alphanumeric, so the [^a-z0-9]+ regex matches a run of
			// literal hyphens and collapses it to a single '-'. This guarantees the
			// sanitized name can never contain two or more consecutive hyphens.
			name:     "collapses consecutive literal hyphens into a single hyphen",
			input:    "test--.-secret",
			expected: "test-secret",
		},
		{
			name:     "leaves already valid names unchanged",
			input:    "valid-secret-123",
			expected: "valid-secret-123",
		},
		{
			name:     "truncates to 63 characters",
			input:    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-----bb",
			expected: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-b",
		},
		{
			name:     "truncates characters without a trailing hyphen, keeping a valid ending",
			input:    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-----bb",
			expected: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := sanitizeVolumeName(tt.input)
			assert.Equal(t, tt.expected, result, "sanitizeVolumeName(%q) should match expected value", tt.input)

			// Verify DNS-1123 label compliance
			assert.LessOrEqual(t, len(result), 63, "Volume name should not exceed 63 characters")
			assert.Regexp(t, "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$", result, "Volume name should be a valid DNS-1123 label")
		})
	}
}

func TestEndpointName(t *testing.T) {
	originalRegexp := regexp.MustCompile(`[^a-z0-9]+`)
	for _, test := range []struct {
		name string
		want string
	}{
		{"", ""},
		{"a", "a"},
		{"0", "0"},
		{"endpoint123", "endpoint123"},
		{"my-endpoint", "my-endpoint"},
		{"a-0-z-9", "a-0-z-9"},
		{strings.Repeat("a", 1000), strings.Repeat("a", 1000)},
		{"my--endpoint", "my-endpoint"},
		{"my---endpoint", "my-endpoint"},
		{"endpoint--0--0", "endpoint-0-0"},
		{"a--é--b", "a-b"},
		{"a\xff--b", "a-b"},
		{"-endpoint", "endpoint"},
		{"endpoint-", "endpoint"},
		{"--endpoint--", "endpoint"},
		{"-", ""},
		{"---", ""},
		{"My-Endpoint", "my-endpoint"},
		{"ENDPOINT", "endpoint"},
		{"my._ /endpoint!?", "my-endpoint"},
		{"!?", ""},
		{"é-endpoint-界", "endpoint"},
		{"端点", ""},
		{"Kelvin", "kelvin"},
		{"a\x00b", "a-b"},
	} {
		t.Run(test.name, func(t *testing.T) {
			original := strings.Trim(originalRegexp.ReplaceAllString(strings.ToLower(test.name), "-"), "-")
			if got := EndpointName(test.name); got != test.want || got != original {
				t.Fatalf("EndpointName(%q) = %q, want %q (original %q)", test.name, got, test.want, original)
			}
			if test.name == test.want {
				var got string
				allocs := testing.AllocsPerRun(100, func() { got = EndpointName(test.name) })
				if allocs != 0 || got != test.want {
					t.Fatalf("Canonical name %q: got %q with %g allocations, want zero", test.name, got, allocs)
				}
			}
		})
	}
}

// Generated by Codex.
func TestEndpointNameRepeatedHyphensAllocations(t *testing.T) {
	for _, name := range []string{"endpoint--0--0", "--endpoint--", "my---endpoint"} {
		t.Run(name, func(t *testing.T) {
			var got string
			allocs := testing.AllocsPerRun(100, func() { got = EndpointName(name) })
			if allocs > 1 {
				t.Fatalf("EndpointName(%q) = %q with %g allocations, want at most one", name, got, allocs)
			}
		})
	}
}

// Generated by Codex.
func FuzzEndpointName(f *testing.F) {
	for _, name := range []string{"", "endpoint--0--0", "--endpoint--", "A._ /b!?", "a--é--b", "Kelvin", "a\xff--b"} {
		f.Add(name)
	}
	originalRegexp := regexp.MustCompile(`[^a-z0-9]+`)
	f.Fuzz(func(t *testing.T, name string) {
		want := strings.Trim(originalRegexp.ReplaceAllString(strings.ToLower(name), "-"), "-")
		if got := EndpointName(name); got != want {
			t.Fatalf("EndpointName(%q) = %q, want %q", name, got, want)
		}
	})
}
