@startuml

participant Client
participant K8s
participant Controller
box Workspace
participant DevWorkspaceJWTProxy
participant DevWorkspaceSecureServer
end box
participant AuthBridge
participant OpenID

autonumber
skinparam SequenceGroupBodyBackgroundColor transparent

== DevWorkspace Start ==

Client -> K8s: Create started DevWorkspace CR
K8s -> Controller: DevWorkspace CR is created
Controller -> Controller: Start the DevWorkspace
Controller -> Controller: Create keys for jwt token
Controller -[#blue]> DevWorkspaceJWTProxy: Inject public key into DevWorkspace
Controller -> K8s: DevWorkspace is started

== Secure Server Access ==

Client -> DevWorkspaceJWTProxy: Open secure server
DevWorkspaceJWTProxy -> DevWorkspaceJWTProxy: check if cookies are set

DevWorkspaceJWTProxy -> Client: redirects to AuthBridge

Client -> AuthBridge: authenticate on the DevWorkspace

group OAuth flow
AuthBridge -> OpenID: authenticate user
AuthBridge <- OpenID: user is authenticated
end

AuthBridge -[#green]> K8s: read devworkspace with authenticated user + authorize
AuthBridge -[#blue]> DevWorkspaceJWTProxy: set cookies with devworkspace jwt token

AuthBridge -> Client: redirects to devworkspace

Client -> DevWorkspaceJWTProxy: Open a secure server
DevWorkspaceJWTProxy -> DevWorkspaceJWTProxy: Check if cookies are set
DevWorkspaceJWTProxy -> DevWorkspaceSecureServer: proxy request
DevWorkspaceSecureServer -> Client: response

@enduml
