#!/bin/bash
#
# Copyright (c) 2019-2026 Red Hat, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#!/usr/bin/env bash
# only exit with zero if all commands of the pipeline exit successfully
set -o pipefail
# error on unset variables
set -u
# print each command before executing it
set -x

# Source common utilities
source "$(dirname "$0")/common.sh"

# ENV used by PROW ci
export CI="openshift"
# Pod created by openshift ci don't have user. Using this envs should avoid errors with git user.
export GIT_COMMITTER_NAME="CI BOT"
export GIT_COMMITTER_EMAIL="ci_bot@notused.com"

# Che configuration
export CHE_NAMESPACE="${CHE_NAMESPACE:-eclipse-che}"
export MAX_RETRIES=2
export BASE_DELAY=60
export MAX_JITTER=15

# Artifact directory for logs
export ARTIFACT_DIR="${ARTIFACT_DIR:-/tmp/dwo-e2e-artifacts}"
mkdir -p "${ARTIFACT_DIR}"

deployDWO() {
  echo "======== Deploying DevWorkspace Operator ========"
  export NAMESPACE="devworkspace-controller"
  export DWO_IMG="${DEVWORKSPACE_OPERATOR}"

  if ! make install; then
    echo "ERROR: Failed to deploy DevWorkspace Operator"
    bumpPodsInfo "$NAMESPACE"
    return 1
  fi

  echo "======== Verifying DWO deployment ========"
  # Wait for DWO controller to be ready
  if ! kubectl wait --for=condition=available deployment/devworkspace-controller-manager \
    -n "$NAMESPACE" \
    --timeout=300s; then
    echo "ERROR: DWO controller is not ready"
    bumpPodsInfo "$NAMESPACE"
    return 1
  fi

  echo "✅ DevWorkspace Operator deployed successfully"
  return 0
}

# Generated by Claude Sonnet 4.5
verifyOLMHealth() {
  echo "======== Verifying OLM Infrastructure ========"

  # Check catalog-operator is available
  echo "Checking catalog-operator..."
  if ! kubectl wait --for=condition=available deployment/catalog-operator \
    -n openshift-operator-lifecycle-manager \
    --timeout=120s 2>&1; then
    echo "ERROR: catalog-operator is not ready"
    kubectl get deployment/catalog-operator \
      -n openshift-operator-lifecycle-manager -o yaml || true
    return 1
  fi

  # Check olm-operator is available
  echo "Checking olm-operator..."
  if ! kubectl wait --for=condition=available deployment/olm-operator \
    -n openshift-operator-lifecycle-manager \
    --timeout=120s 2>&1; then
    echo "ERROR: olm-operator is not ready"
    kubectl get deployment/olm-operator \
      -n openshift-operator-lifecycle-manager -o yaml || true
    return 1
  fi

  # Verify marketplace is accessible
  echo "Checking openshift-marketplace..."
  if ! kubectl get catalogsources -n openshift-marketplace &>/dev/null; then
    echo "ERROR: Cannot access CatalogSources in openshift-marketplace"
    return 1
  fi

  echo "✅ OLM infrastructure is healthy"
  return 0
}

deployChe() {
  echo "======== Deploying Eclipse Che (attempt $1/$MAX_RETRIES) ========"

  if ! chectl server:deploy \
    -p openshift \
    --batch \
    --telemetry=off \
    --skip-devworkspace-operator \
    --chenamespace="$CHE_NAMESPACE" \
    --k8spodwaittimeout=86400 \
    --k8spodreadytimeout=86400; then
    echo "ERROR: chectl server:deploy failed"
    return 1
  fi

  echo "✅ chectl server:deploy completed"
  return 0
}

# Generated by Claude Sonnet 4.5
verifyCheDeployment() {
  echo "======== Verifying Che deployment ========"

  # Check if CheCluster CR exists
  if ! kubectl get checluster -n "$CHE_NAMESPACE" &>/dev/null; then
    echo "ERROR: CheCluster CR not found in namespace $CHE_NAMESPACE"
    return 1
  fi

  # Get CheCluster name (usually 'eclipse-che')
  local che_cluster_name
  che_cluster_name=$(kubectl get checluster -n "$CHE_NAMESPACE" -o jsonpath='{.items[0].metadata.name}')

  if [ -z "$che_cluster_name" ]; then
    echo "ERROR: Could not find CheCluster name"
    return 1
  fi

  echo "Found CheCluster: $che_cluster_name"

  # Wait for CheCluster to be available (with timeout)
  echo "Waiting for CheCluster to become available..."
  if ! timeout 600s kubectl wait checluster/"$che_cluster_name" \
    --for=condition=Available \
    --timeout=600s \
    -n "$CHE_NAMESPACE" 2>&1; then
    echo "ERROR: CheCluster did not become available within 10 minutes"

    # Show CheCluster status for debugging
    echo "======== CheCluster Status ========"
    kubectl get checluster "$che_cluster_name" -n "$CHE_NAMESPACE" -o yaml || true

    return 1
  fi

  # Verify CheCluster is running
  local che_running
  che_running=$(kubectl get checluster "$che_cluster_name" -n "$CHE_NAMESPACE" \
    -o jsonpath='{.status.cheClusterRunning}')

  if [ "$che_running" != "true" ]; then
    echo "ERROR: CheCluster status shows not running (cheClusterRunning=$che_running)"
    kubectl describe checluster "$che_cluster_name" -n "$CHE_NAMESPACE" || true
    return 1
  fi

  # Wait for all pods to be ready
  echo "Waiting for all Che pods to be ready..."
  if ! timeout 300s kubectl wait --for=condition=ready pod \
    --all \
    --timeout=300s \
    -n "$CHE_NAMESPACE" 2>&1; then
    echo "WARNING: Not all pods are ready, but CheCluster is available. Proceeding..."
    kubectl get pods -n "$CHE_NAMESPACE" || true
  fi

  echo "✅ Eclipse Che deployment verified successfully"
  return 0
}

# Generated by Claude Sonnet 4.5
collectCheArtifacts() {
  local attempt=$1
  echo "======== Collecting Che artifacts (attempt $attempt) ========"

  # Collect pod info from Che namespace
  bumpPodsInfo "$CHE_NAMESPACE" || true

  # Collect Che operator logs
  local che_operator_logs="${ARTIFACT_DIR}/che-operator-logs-attempt-${attempt}.log"
  echo "Collecting Che operator logs to $che_operator_logs"
  kubectl logs -n "$CHE_NAMESPACE" \
    -l app.kubernetes.io/component=che-operator \
    --tail=1000 > "$che_operator_logs" 2>&1 || true

  # Collect CheCluster CR status
  local checluster_status="${ARTIFACT_DIR}/checluster-status-attempt-${attempt}.yaml"
  echo "Collecting CheCluster status to $checluster_status"
  kubectl get checluster -n "$CHE_NAMESPACE" -o yaml > "$checluster_status" 2>&1 || true

  # Collect OLM-specific diagnostics
  local olm_diagnostics="${ARTIFACT_DIR}/olm-diagnostics-attempt-${attempt}.yaml"
  echo "Collecting OLM diagnostics to $olm_diagnostics"
  {
    echo "=== Subscription ==="
    kubectl get subscription -n "$CHE_NAMESPACE" -o yaml 2>&1 || echo "No subscriptions found"
    echo ""
    echo "=== InstallPlan ==="
    kubectl get installplan -n "$CHE_NAMESPACE" -o yaml 2>&1 || echo "No installplans found"
    echo ""
    echo "=== ClusterServiceVersion ==="
    kubectl get csv -n "$CHE_NAMESPACE" -o yaml 2>&1 || echo "No CSVs found"
    echo ""
    echo "=== CatalogSource ==="
    kubectl get catalogsource -n openshift-marketplace -o yaml 2>&1 || echo "Cannot access catalogsources"
  } > "$olm_diagnostics" 2>&1 || true

  # Collect CatalogSource pod logs
  local catalogsource_logs="${ARTIFACT_DIR}/catalogsource-logs-attempt-${attempt}.log"
  echo "Collecting CatalogSource pod logs to $catalogsource_logs"
  kubectl logs -n openshift-marketplace \
    -l olm.catalogSource=eclipse-che \
    --tail=1000 > "$catalogsource_logs" 2>&1 || true

  # Collect chectl server logs
  echo "Collecting chectl server logs"
  chectl server:logs -n "$CHE_NAMESPACE" -d "${ARTIFACT_DIR}/chectl-logs-attempt-${attempt}" 2>&1 || true

  echo "Artifact collection completed"
}

# Generated by Claude Sonnet 4.5
cleanupFailedChe() {
  echo "======== Cleaning up failed Che deployment ========"
  chectl server:delete -n "$CHE_NAMESPACE" --yes 2>&1 || true

  # Wait for namespace to be cleaned up
  sleep 10
}

# Generated by Claude Sonnet 4.5
deployAndVerifyChe() {
  local attempt

  # Verify OLM infrastructure health before attempting Che deployment
  if ! verifyOLMHealth; then
    echo "❌ ERROR: OLM infrastructure is not healthy, cannot proceed with Che deployment"
    echo "Collecting OLM diagnostics..."
    collectCheArtifacts "olm-check"
    return 1
  fi

  for attempt in $(seq 1 $MAX_RETRIES); do
    echo ""
    echo "========================================"
    echo "Che Deployment Attempt $attempt/$MAX_RETRIES"
    echo "========================================"

    # Try to deploy Che
    if deployChe "$attempt" && verifyCheDeployment; then
      echo "✅ Eclipse Che deployed and verified successfully on attempt $attempt"
      return 0
    fi

    # Deployment or verification failed
    echo "❌ Che deployment failed on attempt $attempt"

    # Collect artifacts before cleanup
    collectCheArtifacts "$attempt"

    # If not the last attempt, clean up and retry
    if [ $attempt -lt $MAX_RETRIES ]; then
      # Calculate exponential backoff with jitter
      local exponential_delay=$((BASE_DELAY * (2 ** (attempt - 1))))
      local jitter=$((RANDOM % MAX_JITTER))
      local delay=$((exponential_delay + jitter))

      echo "Cleaning up failed deployment..."
      cleanupFailedChe

      echo "Retrying in ${delay} seconds..."
      sleep "$delay"
    fi
  done

  echo "❌ ERROR: Che deployment failed after $MAX_RETRIES attempts"
  return 1
}

# Generated by Claude Sonnet 4.5
runHappyPathTest() {
  echo "======== Running Che Happy Path Test ========"
  export CHE_REPO_BRANCH="${CHE_REPO_BRANCH:-main}"

  # Download and run the remote test script
  if ! bash <(curl -s "https://raw.githubusercontent.com/eclipse/che/${CHE_REPO_BRANCH}/tests/devworkspace-happy-path/remote-launch.sh"); then
    echo "ERROR: Happy path test failed"

    # Collect artifacts on test failure
    echo "Collecting artifacts after test failure..."
    collectCheArtifacts "final"

    return 1
  fi

  echo "✅ Happy path test completed successfully"
  return 0
}

# Main execution
# Generated by Claude Sonnet 4.5
main() {
  local exit_code=0

  # Deploy DWO
  if ! deployDWO; then
    echo "❌ FAILED: DevWorkspace Operator deployment"
    exit 1
  fi

  # Deploy and verify Che with retry logic
  if ! deployAndVerifyChe; then
    echo "❌ FAILED: Eclipse Che deployment"
    exit 1
  fi

  # Run the happy path test
  if ! runHappyPathTest; then
    echo "❌ FAILED: Happy path test execution"
    exit 1
  fi

  echo ""
  echo "✅ SUCCESS: All tests passed!"
  return 0
}

# Run main function
main
exit_code=$?

# Ensure we exit with the correct code
exit $exit_code
