apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: devworkspace-controller-view-workspaces
rules:
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  - devworkspacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings
  - devworkspaceoperatorconfigs
  verbs:
  - get
  - list
  - watch
