apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  name: chectl
spec:
  started: true
  devfile:
    apiVersion: 0.0.1
    metadata:
      name: chectl 
    projects:
      - name: chectl
        source:
          type: git
          location: 'https://github.com/che-incubator/chectl.git'
    components:
      - name: theia-ide
        type: cheEditor
        id: org.eclipse.che.editor.theia:next
      - name: exec-plugin
        type: chePlugin
        id: che-machine-exec-plugin:0.0.1
      - name: fortune
        type: chePlugin
        id: org.eclipse.che.samples.container-fortune:0.0.1
      - name: xml
        type: chePlugin
        id: redhat.vscode-xml:0.3.0
      - name: mvn-stack
        type: dockerimage
        image: maven:3.5.4-jdk-8
        command: ['/bin/sh', '-c']
        args: ['tail -f /dev/null']
        volumes:
          - name: mavenrepo
            containerPath: /root/.m2
        endpoints:
          - name: spring-boot
            port: 8080
            attributes:
              path: /api
              protocol: http
              public: "true"
        env:
          - name: TERM
            value: xterm
        mountSources: true
        memoryLimit: 500M
    commands:
      - name: build
        actions:
          - type: exec
            component: theia-ide
            command: yarn
            workdir: /projects/chectl
      - name: test
        actions:
          - type: exec
            component: theia-ide
            command: yarn test
            workdir: /projects/chectl
