kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha1
metadata:
  name: cloud-shell
  annotations:
    controller.devfile.io/restricted-access: "true"
spec:
  started: true
  routingClass: openshift-oauth
  template:
    components:
      - plugin:
          name: cloud-shell
          id: eclipse/cloud-shell/nightly
      - container:
          name: dev
          image: quay.io/eclipse/che-sidecar-openshift-connector:0.1.2-2601509
          memoryLimit: 256Mi
          args: ["tail", "-f", "/dev/null"]
          env:
            - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
              name: PS1
