{
 "title": "DWO",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DevWorkspace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Workspace Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (source) (increase(devworkspace_startup_time_sum[$__interval]))) / (sum by (source) (increase(devworkspace_startup_time_count[$__interval])))",
     "legendFormat": "Average startup time (source={{source}})"
    }
   ]
  },
  {
   "title": "Workspace Starts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (source) (increase(devworkspace_started_total[$__interval]))",
     "legendFormat": "Workspaces started (source={{source}})"
    }
   ]
  },
  {
   "title": "Workspace Startup Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(devworkspace_startup_time_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DevWorkspace Successes/Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(devworkspace_fail_total[$__interval]))",
     "legendFormat": "Failures"
    },
    {
     "expr": "sum(increase(devworkspace_started_success_total[$__interval]))",
     "legendFormat": "Successes"
    }
   ]
  },
  {
   "title": "DevWorkspace Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(devworkspace_fail_total[$__range])) / sum(increase(devworkspace_started_total[$__range])) * 100.0"
    }
   ]
  },
  {
   "title": "DevWorkspace Startup Failure Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(devworkspace_fail_total[$__range])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Operator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Webhooks in Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (webhook) (increase(controller_runtime_webhook_requests_total[$__interval]))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Workqueue Duration",
   "type": "heatmap",
   "description": "How long reconcile requests sit in the workqueue before being handled",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(workqueue_queue_duration_seconds_bucket{name=\"devworkspace\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Webhooks Latency (/mutate)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_latency_seconds_bucket{webhook=\"/mutate\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reconcile Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_time_seconds_bucket{controller=\"devworkspace\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Webhooks Latency (/convert)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_latency_seconds_bucket{webhook=\"/convert\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "description": "How many reconcile requests are in the queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "req" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"devworkspace\"}",
     "legendFormat": "Workqueue depth (DW)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory use ({{job}})" }
   ]
  },
  {
   "title": "Reconcile Counts (DWO)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{controller=\"devworkspace\"}[$__interval])",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}