{
 "title": "Dev Workspace Operator",
 "tags": [ "dev-spaces" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DevWorkspace Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Workspace Start Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum by (source) (increase(devworkspace_startup_time_sum[$__range]))) / (sum by (source) (increase(devworkspace_startup_time_count[$__range])))",
     "legendFormat": "Average startup time (source={{source}})"
    }
   ]
  },
  {
   "title": "Workspace Starts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Workspaces started" }
   ],
   "targets": [
    {
     "expr": "sum by (source) (floor(increase(devworkspace_started_total[$__interval])))",
     "legendFormat": "Workspaces started"
    }
   ]
  },
  {
   "title": "DevWorkspace Successes/Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(devworkspace_started_success_total[$__interval]))",
     "legendFormat": "Successes"
    },
    {
     "expr": "sum(increase(devworkspace_fail_total[$__interval]))",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "DevWorkspace Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(devworkspace_fail_total[$__range])) / sum(increase(devworkspace_started_total[$__range])) * 100.0"
    }
   ]
  },
  {
   "title": "DevWorkspace Failure Reasons",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(devworkspace_fail_total[$__range])) by (reason)"
    }
   ]
  },
  { "title": "Operator Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Webhooks in Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (webhook) (increase(controller_runtime_webhook_requests_total{service=~\"devworkspace.+\"}[$__interval]))",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Webhooks Latency (/mutate)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_webhook_latency_seconds_bucket{webhook=\"/mutate\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "graph",
   "description": "How many reconcile requests are in the queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "req" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"devworkspace\"}",
     "legendFormat": "Workqueue depth (DW)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\"devworkspace.+\"}",
     "legendFormat": "Memory use ({{job}})"
    }
   ]
  },
  {
   "title": "Reconcile Counts (DWO)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{controller=\"devworkspace\"}[$__interval])",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}