// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package solvers

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	controllerv1alpha1 "github.com/devfile/devworkspace-operator/apis/controller/v1alpha1"
	"github.com/devfile/devworkspace-operator/pkg/common"
)

// Generated by Codex.
func TestClusterSolverGetSpecObjectsServingCertMounts(t *testing.T) {
	workspaceMeta := DevWorkspaceMetadata{
		DevWorkspaceId:   "workspace-id",
		DevWorkspaceName: "workspace",
		Namespace:        "workspace-namespace",
		PodSelector:      map[string]string{"workspace": "workspace-id"},
	}
	endpoints := map[string]controllerv1alpha1.EndpointList{
		"main": {
			{
				Name:       "api",
				TargetPort: 8080,
				Exposure:   controllerv1alpha1.PublicEndpointExposure,
				Attributes: controllerv1alpha1.Attributes{}.
					PutBoolean(string(controllerv1alpha1.DiscoverableAttribute), true),
			},
			{
				Name:       "database",
				TargetPort: 5432,
				Exposure:   controllerv1alpha1.InternalEndpointExposure,
				Attributes: controllerv1alpha1.Attributes{}.
					PutBoolean(string(controllerv1alpha1.DiscoverableAttribute), true),
			},
		},
	}
	aggregateServiceName := common.ServiceName(workspaceMeta.DevWorkspaceId)

	tests := []struct {
		name           string
		tls            bool
		expectedMounts map[string]string
	}{
		{
			name: "TLS discoverable endpoint certificates use distinct mounts",
			tls:  true,
			expectedMounts: map[string]string{
				"/var/serving-cert/":          aggregateServiceName,
				"/var/serving-cert/api/":      "api",
				"/var/serving-cert/database/": "database",
			},
		},
		{
			name: "plaintext routing requests no certificates",
			tls:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			scheme := runtime.NewScheme()
			assert.NoError(t, corev1.AddToScheme(scheme))
			solver := NewClusterSolver(fake.NewClientBuilder().WithScheme(scheme).Build(), tt.tls)
			routing := &controllerv1alpha1.DevWorkspaceRouting{
				Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{
					Endpoints:   endpoints,
					PodSelector: workspaceMeta.PodSelector,
				},
			}

			objects, err := solver.GetSpecObjects(routing, workspaceMeta)
			if !assert.NoError(t, err) {
				return
			}

			if !tt.tls {
				assert.Empty(t, objects.PodAdditions.Volumes)
				assert.Empty(t, objects.PodAdditions.VolumeMounts)
				return
			}

			assert.Len(t, objects.Services, 3)
			for _, service := range objects.Services {
				assert.Equal(t, service.Name, service.Annotations[serviceServingCertAnnot])
			}

			volumeSecrets := make(map[string]string, len(objects.PodAdditions.Volumes))
			for _, volume := range objects.PodAdditions.Volumes {
				volumeSecrets[volume.Name] = volume.Secret.SecretName
			}

			actualMounts := make(map[string]string, len(objects.PodAdditions.VolumeMounts))
			for _, mount := range objects.PodAdditions.VolumeMounts {
				if _, exists := actualMounts[mount.MountPath]; exists {
					assert.Failf(t, "duplicate serving certificate mount path", "path %q is used more than once", mount.MountPath)
				}
				actualMounts[mount.MountPath] = volumeSecrets[mount.Name]
			}

			assert.Len(t, actualMounts, 3)
			assert.Equal(t, tt.expectedMounts, actualMounts)
		})
	}
}

// Generated by Codex.
func TestClusterSolverGetSpecObjectsLongServingCertVolumeNames(t *testing.T) {
	longEndpointName := strings.Repeat("a", 39)
	derivedShortEndpointName := "b4d5e56e929ba4cda349"
	endpointNames := []string{
		strings.Repeat("a", 37),
		strings.Repeat("b", 38),
		longEndpointName,
		strings.Repeat("d", 63),
		strings.Repeat("x", 62) + "a",
		strings.Repeat("x", 62) + "b",
		derivedShortEndpointName,
	}
	endpoints := make(controllerv1alpha1.EndpointList, len(endpointNames))
	expectedMounts := map[string]string{
		"/var/serving-cert/": common.ServiceName("workspace-id"),
	}
	for i, name := range endpointNames {
		endpoints[i] = controllerv1alpha1.Endpoint{
			Name:       name,
			TargetPort: 7000 + i,
			Exposure:   controllerv1alpha1.InternalEndpointExposure,
			Attributes: controllerv1alpha1.Attributes{}.
				PutBoolean(string(controllerv1alpha1.DiscoverableAttribute), true),
		}
		expectedMounts["/var/serving-cert/"+name+"/"] = name
	}

	workspaceMeta := DevWorkspaceMetadata{
		DevWorkspaceId:   "workspace-id",
		DevWorkspaceName: "workspace",
		Namespace:        "workspace-namespace",
		PodSelector:      map[string]string{"workspace": "workspace-id"},
	}
	scheme := runtime.NewScheme()
	assert.NoError(t, corev1.AddToScheme(scheme))
	solver := NewClusterSolver(fake.NewClientBuilder().WithScheme(scheme).Build(), true)
	routing := &controllerv1alpha1.DevWorkspaceRouting{
		Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{
			Endpoints:   map[string]controllerv1alpha1.EndpointList{"main": endpoints},
			PodSelector: workspaceMeta.PodSelector,
		},
	}

	objects, err := solver.GetSpecObjects(routing, workspaceMeta)
	if !assert.NoError(t, err) {
		return
	}

	assert.Len(t, objects.Services, len(endpointNames)+1)
	assert.Len(t, objects.PodAdditions.Volumes, len(endpointNames)+1)
	assert.Len(t, objects.PodAdditions.VolumeMounts, len(endpointNames)+1)

	volumeSecrets := make(map[string]string, len(objects.PodAdditions.Volumes))
	volumeNamesBySecret := make(map[string]string, len(objects.PodAdditions.Volumes))
	for _, volume := range objects.PodAdditions.Volumes {
		if !assert.NotContains(t, volumeSecrets, volume.Name) {
			continue
		}
		assert.LessOrEqual(t, len(volume.Name), 63)
		if !assert.NotNil(t, volume.Secret) {
			continue
		}
		volumeSecrets[volume.Name] = volume.Secret.SecretName
		volumeNamesBySecret[volume.Secret.SecretName] = volume.Name
	}
	assert.Equal(t, "devworkspace-serving-cert-"+endpointNames[0], volumeNamesBySecret[endpointNames[0]])
	assert.Equal(t, "devworkspace-cert-b4d5e56e929ba4cda349", volumeNamesBySecret[longEndpointName])
	assert.Equal(t, "devworkspace-serving-cert-"+derivedShortEndpointName, volumeNamesBySecret[derivedShortEndpointName])

	actualMounts := make(map[string]string, len(objects.PodAdditions.VolumeMounts))
	for _, mount := range objects.PodAdditions.VolumeMounts {
		if !assert.NotContains(t, actualMounts, mount.MountPath) {
			continue
		}
		secretName, exists := volumeSecrets[mount.Name]
		if !assert.True(t, exists, "mount %q references volume %q", mount.MountPath, mount.Name) {
			continue
		}
		actualMounts[mount.MountPath] = secretName
	}
	assert.Equal(t, expectedMounts, actualMounts)
}
