// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package solvers

import (
	"testing"

	"github.com/stretchr/testify/assert"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	controllerv1alpha1 "github.com/devfile/devworkspace-operator/apis/controller/v1alpha1"
)

// Generated by Codex.
func TestClusterSolverRejectsDiscoverableEndpointUsingWorkspaceServiceName(t *testing.T) {
	for _, tt := range []struct {
		name string
		tls  bool
	}{
		{name: "plaintext", tls: false},
		{name: "TLS", tls: true},
	} {
		t.Run(tt.name, func(t *testing.T) {
			scheme := runtime.NewScheme()
			assert.NoError(t, corev1.AddToScheme(scheme))
			solver := NewClusterSolver(fake.NewClientBuilder().WithScheme(scheme).Build(), tt.tls)
			const reservedServiceName = "mine-service"
			routing := &controllerv1alpha1.DevWorkspaceRouting{
				Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{
					Endpoints: map[string]controllerv1alpha1.EndpointList{
						"machine": {{
							Name:       reservedServiceName,
							TargetPort: 8080,
							Exposure:   controllerv1alpha1.InternalEndpointExposure,
							Attributes: controllerv1alpha1.Attributes{}.
								PutBoolean(string(controllerv1alpha1.DiscoverableAttribute), true),
						}},
					},
				},
			}
			objects, err := solver.GetSpecObjects(routing, DevWorkspaceMetadata{
				DevWorkspaceId: "mine",
				Namespace:      "test-namespace",
			})

			var invalid *RoutingInvalid
			assert.ErrorAs(t, err, &invalid)
			if assert.NotNil(t, invalid) {
				assert.Contains(t, invalid.Reason, "discoverable endpoint")
				assert.Contains(t, invalid.Reason, reservedServiceName)
			}
			assert.Empty(t, objects.Services)
		})
	}
}
