// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package devworkspacerouting

import (
	"context"
	"testing"

	"github.com/go-logr/logr"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/utils/ptr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	controllerv1alpha1 "github.com/devfile/devworkspace-operator/apis/controller/v1alpha1"
	"github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/solvers"
	"github.com/devfile/devworkspace-operator/pkg/constants"
	"github.com/devfile/devworkspace-operator/pkg/infrastructure"
)

// Generated by Codex
func TestReconcileMarksSynchronizationConflictFailed(t *testing.T) {
	infrastructure.InitializeForTesting(infrastructure.Kubernetes)
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	if err := controllerv1alpha1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	routing := &controllerv1alpha1.DevWorkspaceRouting{ObjectMeta: metav1.ObjectMeta{Name: "routing-mine", Namespace: "ns", UID: "mine-routing"}, Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{DevWorkspaceId: "mine", RoutingClass: controllerv1alpha1.DevWorkspaceRoutingCluster, Endpoints: map[string]controllerv1alpha1.EndpointList{"main": {{Name: "api", TargetPort: 8080, Exposure: controllerv1alpha1.InternalEndpointExposure, Attributes: controllerv1alpha1.Attributes{}.PutBoolean("discoverable", true)}}}}}
	foreign := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "api", Namespace: "ns", UID: "foreign-service"}, Spec: corev1.ServiceSpec{Selector: map[string]string{"app": "foreign"}}}
	backing := fake.NewClientBuilder().WithScheme(scheme).WithStatusSubresource(routing).WithObjects(routing, foreign).Build()
	r := DevWorkspaceRoutingReconciler{Client: serviceLabelFilteredClient{backing}, NonCachingClient: backing, Scheme: scheme, Log: logr.Discard(), SolverGetter: &solvers.SolverGetter{}}
	_, err := r.Reconcile(context.Background(), ctrl.Request{NamespacedName: client.ObjectKeyFromObject(routing)})
	if err != nil {
		t.Fatal(err)
	}
	actualRouting := &controllerv1alpha1.DevWorkspaceRouting{}
	if err := backing.Get(context.Background(), client.ObjectKeyFromObject(routing), actualRouting); err != nil {
		t.Fatal(err)
	}
	if actualRouting.Status.Phase != controllerv1alpha1.RoutingFailed {
		t.Fatalf("want permanent conflict, got %s: %s", actualRouting.Status.Phase, actualRouting.Status.Message)
	}
	actual := &corev1.Service{}
	if err := backing.Get(context.Background(), client.ObjectKeyFromObject(foreign), actual); err != nil {
		t.Fatalf("foreign Service deleted: %v", err)
	}
	if actual.Spec.Selector["app"] != "foreign" {
		t.Fatal("foreign Service modified")
	}
}

// Generated by Codex
func TestSyncServicesDoesNotDeleteForeignServiceWithWorkspaceLabel(t *testing.T) {
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	foreign := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "unused", Namespace: "ns", UID: "foreign-service", Labels: map[string]string{constants.DevWorkspaceIDLabel: "mine"}, OwnerReferences: []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "other-routing", Controller: ptr.To(true)}}}}
	cl := fake.NewClientBuilder().WithScheme(scheme).WithObjects(foreign).Build()
	r := DevWorkspaceRoutingReconciler{Client: cl, Scheme: scheme, Log: logr.Discard()}
	routing := &controllerv1alpha1.DevWorkspaceRouting{ObjectMeta: metav1.ObjectMeta{Name: "routing-mine", Namespace: "ns", UID: "mine-routing"}, Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{DevWorkspaceId: "mine"}}
	_, _, err := r.syncServices(routing, nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := cl.Get(context.Background(), client.ObjectKeyFromObject(foreign), &corev1.Service{}); err != nil {
		t.Fatalf("foreign Service deleted: %v", err)
	}
}

// Generated by Codex
func TestSyncServicesDeletesOwnedService(t *testing.T) {
	scheme := runtime.NewScheme()
	if err := corev1.AddToScheme(scheme); err != nil {
		t.Fatal(err)
	}
	owned := &corev1.Service{ObjectMeta: metav1.ObjectMeta{Name: "unused", Namespace: "ns", UID: "owned-service", Labels: map[string]string{constants.DevWorkspaceIDLabel: "mine"}, OwnerReferences: []metav1.OwnerReference{{Kind: "DevWorkspaceRouting", UID: "mine-routing", Controller: ptr.To(true)}}}}
	cl := fake.NewClientBuilder().WithScheme(scheme).WithObjects(owned).Build()
	r := DevWorkspaceRoutingReconciler{Client: cl, Scheme: scheme, Log: logr.Discard()}
	routing := &controllerv1alpha1.DevWorkspaceRouting{ObjectMeta: metav1.ObjectMeta{Name: "routing-mine", Namespace: "ns", UID: "mine-routing"}, Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{DevWorkspaceId: "mine"}}
	ready, _, err := r.syncServices(routing, nil)
	if err != nil || ready {
		t.Fatalf("want pending deletion, got ready=%v err=%v", ready, err)
	}
	if err := cl.Get(context.Background(), client.ObjectKeyFromObject(owned), &corev1.Service{}); !apierrors.IsNotFound(err) {
		t.Fatalf("owned Service still exists: %v", err)
	}
}

// Generated by Codex
type serviceLabelFilteredClient struct{ client.Client }

func (c serviceLabelFilteredClient) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	if err := c.Client.Get(ctx, key, obj, opts...); err != nil {
		return err
	}
	_, labeled := obj.GetLabels()[constants.DevWorkspaceIDLabel]
	if _, ok := obj.(*corev1.Service); ok && !labeled {
		return apierrors.NewNotFound(schema.GroupResource{Resource: "services"}, key.Name)
	}
	return nil
}
