// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package devworkspacerouting

import (
	"context"
	"testing"

	"github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/utils/ptr"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	controllerv1alpha1 "github.com/devfile/devworkspace-operator/apis/controller/v1alpha1"
	"github.com/devfile/devworkspace-operator/controllers/controller/devworkspacerouting/solvers"
	"github.com/devfile/devworkspace-operator/pkg/common"
	"github.com/devfile/devworkspace-operator/pkg/constants"
	"github.com/devfile/devworkspace-operator/pkg/infrastructure"
)

// Generated by Codex.
func TestReconcileUsesDevWorkspaceOwnerName(t *testing.T) {
	infrastructure.InitializeForTesting(infrastructure.Kubernetes)
	g := NewWithT(t)
	scheme := runtime.NewScheme()
	g.Expect(corev1.AddToScheme(scheme)).To(Succeed())
	g.Expect(networkingv1.AddToScheme(scheme)).To(Succeed())
	g.Expect(controllerv1alpha1.AddToScheme(scheme)).To(Succeed())

	firstRouting := workspaceNameTestRouting("routing-first-route", "workspace-id-first", "real-first-workspace")
	secondRouting := workspaceNameTestRouting("routing-second-route", "workspace-id-second", "real-second-workspace")
	fakeClient := fake.NewClientBuilder().WithScheme(scheme).
		WithStatusSubresource(&controllerv1alpha1.DevWorkspaceRouting{}).
		WithObjects(firstRouting, secondRouting).Build()
	reconciler := &DevWorkspaceRoutingReconciler{
		Client:           fakeClient,
		NonCachingClient: fakeClient,
		Log:              ctrl.Log,
		Scheme:           scheme,
		SolverGetter:     &solvers.SolverGetter{},
	}
	ctx := context.Background()

	for range 3 {
		result, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: client.ObjectKeyFromObject(firstRouting)})
		g.Expect(err).To(Succeed())
		if !result.Requeue {
			break
		}
	}

	service := &corev1.Service{}
	serviceKey := client.ObjectKey{Namespace: firstRouting.Namespace, Name: common.EndpointName("api")}
	g.Expect(fakeClient.Get(ctx, serviceKey, service)).To(Succeed())
	g.Expect(service.Labels).To(HaveKeyWithValue(constants.DevWorkspaceNameLabel, "real-first-workspace"))

	_, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: client.ObjectKeyFromObject(secondRouting)})
	g.Expect(err).To(Succeed())
	storedRouting := &controllerv1alpha1.DevWorkspaceRouting{}
	g.Expect(fakeClient.Get(ctx, client.ObjectKeyFromObject(secondRouting), storedRouting)).To(Succeed())
	g.Expect(storedRouting.Status.Phase).To(Equal(controllerv1alpha1.RoutingFailed))
	g.Expect(storedRouting.Status.Message).To(ContainSubstring("real-first-workspace"))
	g.Expect(storedRouting.Status.Message).NotTo(ContainSubstring(firstRouting.Name))
}

// Generated by Codex.
func TestReconcileRepairsOwnedDiscoverableServiceWithStaleWorkspaceID(t *testing.T) {
	tests := []struct {
		name             string
		workspaceIDLabel string
		includeIDLabel   bool
	}{
		{name: "wrong workspace ID label", workspaceIDLabel: "stale-workspace-id", includeIDLabel: true},
		{name: "missing workspace ID label"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			infrastructure.InitializeForTesting(infrastructure.Kubernetes)
			g := NewWithT(t)
			scheme := runtime.NewScheme()
			g.Expect(corev1.AddToScheme(scheme)).To(Succeed())
			g.Expect(networkingv1.AddToScheme(scheme)).To(Succeed())
			g.Expect(controllerv1alpha1.AddToScheme(scheme)).To(Succeed())

			routing := workspaceNameTestRouting("routing-stale-id", "workspace-id", "real-workspace")
			g.Expect(routing.UID).NotTo(BeEmpty())
			serviceLabels := map[string]string{constants.DevWorkspaceNameLabel: "real-workspace"}
			if tt.includeIDLabel {
				serviceLabels[constants.DevWorkspaceIDLabel] = tt.workspaceIDLabel
			}
			controller := true
			discoverableService := &corev1.Service{
				ObjectMeta: metav1.ObjectMeta{
					Name:      common.EndpointName("api"),
					Namespace: routing.Namespace,
					UID:       "existing-service-uid",
					Labels:    serviceLabels,
					OwnerReferences: []metav1.OwnerReference{{
						APIVersion: controllerv1alpha1.GroupVersion.String(),
						Kind:       "DevWorkspaceRouting",
						Name:       routing.Name,
						UID:        routing.UID,
						Controller: &controller,
					}},
				},
				Spec: corev1.ServiceSpec{
					Type:      corev1.ServiceTypeClusterIP,
					ClusterIP: "10.0.0.9",
					Selector:  routing.Spec.PodSelector,
					Ports: []corev1.ServicePort{{
						Name:       common.EndpointName("api"),
						Protocol:   corev1.ProtocolTCP,
						Port:       8080,
						TargetPort: intstr.FromInt(8080),
					}},
				},
			}
			fakeClient := fake.NewClientBuilder().WithScheme(scheme).
				WithStatusSubresource(&controllerv1alpha1.DevWorkspaceRouting{}).
				WithObjects(routing, discoverableService).Build()
			reconciler := &DevWorkspaceRoutingReconciler{
				Client:           fakeClient,
				NonCachingClient: fakeClient,
				Log:              ctrl.Log,
				Scheme:           scheme,
				SolverGetter:     &solvers.SolverGetter{},
			}
			ctx := context.Background()

			for range 3 {
				result, err := reconciler.Reconcile(ctx, ctrl.Request{NamespacedName: client.ObjectKeyFromObject(routing)})
				g.Expect(err).To(Succeed())
				if !result.Requeue {
					break
				}
			}

			storedService := &corev1.Service{}
			serviceKey := client.ObjectKeyFromObject(discoverableService)
			g.Expect(fakeClient.Get(ctx, serviceKey, storedService)).To(Succeed())
			g.Expect(storedService.Labels).To(HaveKeyWithValue(constants.DevWorkspaceIDLabel, routing.Spec.DevWorkspaceId))
			g.Expect(storedService.UID).To(Equal(discoverableService.UID))
			g.Expect(storedService.Spec.ClusterIP).To(Equal(discoverableService.Spec.ClusterIP))
			storedRouting := &controllerv1alpha1.DevWorkspaceRouting{}
			g.Expect(fakeClient.Get(ctx, client.ObjectKeyFromObject(routing), storedRouting)).To(Succeed())
			g.Expect(storedRouting.Status.Phase).NotTo(Equal(controllerv1alpha1.RoutingFailed))
		})
	}
}

// Generated by Codex.
func TestWorkspaceNameRequiresDevWorkspaceControllerOwner(t *testing.T) {
	controller := true
	nonController := false
	tests := []struct {
		name            string
		ownerReferences []metav1.OwnerReference
		want            string
	}{
		{name: "no owner"},
		{
			name: "non-controller owner",
			ownerReferences: []metav1.OwnerReference{{
				APIVersion: v1alpha2.SchemeGroupVersion.String(),
				Kind:       "DevWorkspace",
				Name:       "ignored-workspace",
				Controller: &nonController,
			}},
		},
		{
			name: "wrong kind",
			ownerReferences: []metav1.OwnerReference{{
				APIVersion: v1alpha2.SchemeGroupVersion.String(),
				Kind:       "Pod",
				Name:       "ignored-pod",
				Controller: &controller,
			}},
		},
		{
			name: "wrong API group",
			ownerReferences: []metav1.OwnerReference{{
				APIVersion: controllerv1alpha1.GroupVersion.String(),
				Kind:       "DevWorkspace",
				Name:       "ignored-workspace",
				Controller: &controller,
			}},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g := NewWithT(t)
			routing := &controllerv1alpha1.DevWorkspaceRouting{ObjectMeta: metav1.ObjectMeta{OwnerReferences: tt.ownerReferences}}
			g.Expect(workspaceName(routing)).To(Equal(tt.want))
		})
	}
}

// Generated by Codex.
func workspaceNameTestRouting(name, workspaceID, workspaceName string) *controllerv1alpha1.DevWorkspaceRouting {
	return &controllerv1alpha1.DevWorkspaceRouting{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: "test-namespace",
			UID:       types.UID(name + "-uid"),
			OwnerReferences: []metav1.OwnerReference{{
				APIVersion: v1alpha2.SchemeGroupVersion.String(),
				Kind:       "DevWorkspace",
				Name:       workspaceName,
				UID:        types.UID(workspaceID),
				Controller: ptr.To(true),
			}},
		},
		Spec: controllerv1alpha1.DevWorkspaceRoutingSpec{
			DevWorkspaceId: workspaceID,
			RoutingClass:   controllerv1alpha1.DevWorkspaceRoutingCluster,
			PodSelector:    map[string]string{constants.DevWorkspaceIDLabel: workspaceID},
			Endpoints: map[string]controllerv1alpha1.EndpointList{
				"machine": {{
					Name:       "api",
					TargetPort: 8080,
					Exposure:   controllerv1alpha1.InternalEndpointExposure,
					Attributes: controllerv1alpha1.Attributes{}.
						PutBoolean(string(controllerv1alpha1.DiscoverableAttribute), true),
				}},
			},
		},
	}
}
