// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package handler

import (
	"context"
	"errors"
	"fmt"
	"testing"

	dwv2 "github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2"
	"github.com/stretchr/testify/require"
	admissionv1 "k8s.io/api/admission/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

type endpointIndexRegistration struct {
	object  client.Object
	field   string
	extract client.IndexerFunc
	err     error
}

func (r *endpointIndexRegistration) IndexField(_ context.Context, object client.Object, field string, extract client.IndexerFunc) error {
	r.object, r.field, r.extract = object, field, extract
	return r.err
}

// Generated by Codex.
func newIndexedWorkspaceClientBuilder(t *testing.T, scheme *runtime.Scheme) *fake.ClientBuilder {
	t.Helper()
	registration := &endpointIndexRegistration{}
	require.NoError(t, RegisterDiscoverableEndpointIndex(context.Background(), registration))
	return fake.NewClientBuilder().WithScheme(scheme).WithIndex(registration.object, registration.field, registration.extract)
}

func TestRegisterDiscoverableEndpointIndexFailure(t *testing.T) {
	err := errors.New("index unavailable")
	require.ErrorIs(t, RegisterDiscoverableEndpointIndex(context.Background(), &endpointIndexRegistration{err: err}), err)
}

// Generated by Codex.
func TestValidateEndpointsListFailure(t *testing.T) {
	scheme := runtime.NewScheme()
	require.NoError(t, dwv2.AddToScheme(scheme))
	workspace := setupWorkspace(t, "incoming", "incoming-uid", "test-namespace")
	err := errors.New("list unavailable")
	handler := &WebhookHandler{Client: endpointListFailureClient{err: err}, Decoder: admission.NewDecoder(scheme)}
	conflict, got := handler.validateEndpoints(context.Background(), workspace, discoverableEndpointNames(workspace))
	require.ErrorIs(t, got, err)
	require.Nil(t, conflict)
	response := handler.ValidateDevfile(context.Background(), admission.Request{AdmissionRequest: admissionv1.AdmissionRequest{
		Operation: admissionv1.Create,
		Object:    newRawExtension(t, workspace),
	}})
	require.False(t, response.Allowed)
	require.EqualValues(t, 500, response.Result.Code)
	require.Contains(t, response.Result.Message, err.Error())
}

type endpointListFailureClient struct {
	client.Client
	err error
}

func (c endpointListFailureClient) List(context.Context, client.ObjectList, ...client.ListOption) error {
	return c.err
}

// Generated by Codex.
func TestValidateEndpointsUsesUniqueIndexedQueries(t *testing.T) {
	scheme := runtime.NewScheme()
	require.NoError(t, dwv2.AddToScheme(scheme))
	workspace := setupWorkspace(t, "incoming", "incoming-uid", "test-namespace")
	endpoint := workspace.Spec.Template.Components[0].Container.Endpoints[0]
	endpoint.Name = "unique--endpoint"
	workspace.Spec.Template.Components[0].Container.Endpoints = append(
		workspace.Spec.Template.Components[0].Container.Endpoints, endpoint, endpoint)
	registration := &endpointIndexRegistration{}
	require.NoError(t, RegisterDiscoverableEndpointIndex(context.Background(), registration))
	require.ElementsMatch(t, []string{"test-endpoint", "unique-endpoint"}, registration.extract(workspace))
	indexed := newIndexedWorkspaceClientBuilder(t, scheme).WithObjects(workspace).Build()
	queries := &endpointQueryClient{Client: indexed}
	handler := &WebhookHandler{Client: queries}
	conflict, err := handler.validateEndpoints(context.Background(), workspace, discoverableEndpointNames(workspace))
	require.NoError(t, err)
	require.Nil(t, conflict)
	require.ElementsMatch(t, []string{"test-endpoint", "unique-endpoint"}, queries.names)
}

type endpointQueryClient struct {
	client.Client
	names []string
}

// Generated by Codex.
func (c *endpointQueryClient) List(ctx context.Context, out client.ObjectList, opts ...client.ListOption) error {
	options := (&client.ListOptions{}).ApplyOptions(opts)
	if options.Namespace != "test-namespace" || options.FieldSelector == nil {
		return fmt.Errorf("endpoint queries must be namespace-scoped and indexed")
	}
	name, exact := options.FieldSelector.RequiresExactMatch("controller.devfile.io/discoverable-endpoint")
	if !exact {
		return fmt.Errorf("endpoint queries must select an exact name")
	}
	c.names = append(c.names, name)
	return c.Client.List(ctx, out, opts...)
}
