// Copyright (c) 2019-2026 Red Hat, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package handler

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"

	dwv2 "github.com/devfile/api/v2/pkg/apis/workspaces/v1alpha2"
	"github.com/devfile/api/v2/pkg/attributes"
	. "github.com/onsi/gomega"
	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/rest"
	restfake "k8s.io/client-go/rest/fake"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// newEndpointCache uses the real informer, index, and cache reader. Only the API
// transport is synthetic; queries and copies do not pass through a fake client.
// Generated by Codex.
func newEndpointCache(tb testing.TB, peers []dwv2.DevWorkspace) (cache.Cache, *watch.RaceFreeFakeWatcher) {
	tb.Helper()
	scheme := runtime.NewScheme()
	require.NoError(tb, dwv2.AddToScheme(scheme))
	mapper := meta.NewDefaultRESTMapper([]schema.GroupVersion{dwv2.SchemeGroupVersion})
	mapper.Add(dwv2.SchemeGroupVersion.WithKind("DevWorkspace"), meta.RESTScopeNamespace)
	events := watch.NewRaceFreeFake()
	ready := make(chan struct{})
	list := &dwv2.DevWorkspaceList{
		TypeMeta: metav1.TypeMeta{APIVersion: dwv2.SchemeGroupVersion.String(), Kind: "DevWorkspaceList"},
		ListMeta: metav1.ListMeta{ResourceVersion: "1"},
		Items:    peers,
	}
	initial, err := json.Marshal(list)
	require.NoError(tb, err)
	httpClient := restfake.CreateHTTPClient(func(req *http.Request) (*http.Response, error) {
		if req.Method != http.MethodGet || !strings.HasSuffix(req.URL.Path, "/devworkspaces") {
			return nil, fmt.Errorf("unexpected cache request: %s %s", req.Method, req.URL)
		}
		body := io.NopCloser(bytes.NewReader(initial))
		if req.URL.Query().Get("watch") == "true" {
			reader, writer := io.Pipe()
			body = reader
			go func() {
				defer writer.Close()
				encoder := json.NewEncoder(writer)
				// Support client-go's streaming initial list as well as List+Watch.
				if req.URL.Query().Get("sendInitialEvents") == "true" {
					for i := range peers {
						if err := encoder.Encode(metav1.WatchEvent{Type: string(watch.Added), Object: runtime.RawExtension{Object: &peers[i]}}); err != nil {
							return
						}
					}
					bookmark := &dwv2.DevWorkspace{
						TypeMeta:   metav1.TypeMeta{APIVersion: dwv2.SchemeGroupVersion.String(), Kind: "DevWorkspace"},
						ObjectMeta: metav1.ObjectMeta{ResourceVersion: "1", Annotations: map[string]string{"k8s.io/initial-events-end": "true"}},
					}
					if err := encoder.Encode(metav1.WatchEvent{Type: string(watch.Bookmark), Object: runtime.RawExtension{Object: bookmark}}); err != nil {
						return
					}
				}
				close(ready)
				for {
					select {
					case <-req.Context().Done():
						return
					case event, ok := <-events.ResultChan():
						if !ok {
							return
						}
						if err := encoder.Encode(metav1.WatchEvent{Type: string(event.Type), Object: runtime.RawExtension{Object: event.Object}}); err != nil {
							return
						}
					}
				}
			}()
		}
		return &http.Response{StatusCode: http.StatusOK, Header: http.Header{"Content-Type": {"application/json"}}, Body: body}, nil
	})
	ctx, cancel := context.WithCancel(context.Background())
	cached, err := cache.New(&rest.Config{Host: "https://endpoint-cache.test"}, cache.Options{
		Scheme: scheme, Mapper: mapper, HTTPClient: httpClient,
	})
	require.NoError(tb, err)
	require.NoError(tb, RegisterDiscoverableEndpointIndex(ctx, cached))
	stopped := make(chan error, 1)
	go func() { stopped <- cached.Start(ctx) }()
	tb.Cleanup(func() {
		cancel()
		events.Stop()
		select {
		case err := <-stopped:
			require.NoError(tb, err)
		case <-time.After(10 * time.Second):
			tb.Error("endpoint cache did not stop")
		}
	})
	syncCtx, cancelSync := context.WithTimeout(ctx, 10*time.Second)
	defer cancelSync()
	require.True(tb, cached.WaitForCacheSync(syncCtx), "endpoint cache did not sync")
	select {
	case <-ready:
	case <-syncCtx.Done():
		tb.Fatal("endpoint watch did not start")
	}
	return cached, events
}

// Generated by Codex.
func TestDiscoverableEndpointCacheLifecycle(t *testing.T) {
	cached, events := newEndpointCache(t, nil)
	g := NewWithT(t)
	query := func(namespace, name string) []dwv2.DevWorkspace {
		list := &dwv2.DevWorkspaceList{}
		require.NoError(t, cached.List(context.Background(), list, client.InNamespace(namespace),
			client.MatchingFields{discoverableEndpointIndex: name}))
		return list.Items
	}
	peer := setupWorkspace(t, "peer", "peer-uid", "test-namespace")
	peer.ResourceVersion = "2"
	peer.Spec.Template.Components[0].Container.Env = []dwv2.EnvVar{{Name: "ORIGINAL", Value: "original"}}
	events.Add(peer.DeepCopy())
	g.Eventually(func() []dwv2.DevWorkspace { return query("test-namespace", "test-endpoint") }, 5*time.Second).Should(HaveLen(1))
	otherNamespace := peer.DeepCopy()
	otherNamespace.Namespace = "other-namespace"
	otherNamespace.UID = "other-uid"
	events.Add(otherNamespace)
	g.Eventually(func() []dwv2.DevWorkspace { return query("other-namespace", "test-endpoint") }, 5*time.Second).Should(HaveLen(1))
	items := query("test-namespace", "test-endpoint")
	require.Len(t, items, 1)
	require.Equal(t, peer.UID, items[0].UID)
	container := items[0].Spec.Template.Components[0].Container
	container.Endpoints[0].Name = "mutated"
	container.Endpoints[0].Attributes = container.Endpoints[0].Attributes.PutBoolean("discoverable", false)
	container.Env[0].Value = "mutated"
	original := query("test-namespace", "test-endpoint")[0].Spec.Template.Components[0].Container
	require.Equal(t, "test-endpoint", original.Endpoints[0].Name)
	require.True(t, original.Endpoints[0].Attributes.GetBoolean("discoverable", nil))
	require.Equal(t, "original", original.Env[0].Value)

	peer.ResourceVersion = "3"
	peer.Spec.Template.Components[0].Container.Endpoints[0].Name = "updated--endpoint"
	peer.Spec.Template.Components[0].Container.Endpoints[0].Attributes = attributes.Attributes{}.PutString("discoverable", "true")
	events.Modify(peer.DeepCopy())
	g.Eventually(func() []dwv2.DevWorkspace { return query("test-namespace", "updated-endpoint") }, 5*time.Second).Should(HaveLen(1))
	require.Empty(t, query("test-namespace", "test-endpoint"))
	peer.ResourceVersion = "4"
	peer.Spec.Template.Components[0].Container.Endpoints[0].Exposure = dwv2.NoneEndpointExposure
	events.Modify(peer.DeepCopy())
	g.Eventually(func() []dwv2.DevWorkspace { return query("test-namespace", "updated-endpoint") }, 5*time.Second).Should(BeEmpty())
	peer.ResourceVersion = "5"
	peer.Spec.Template.Components[0].Container.Endpoints[0].Exposure = dwv2.InternalEndpointExposure
	events.Modify(peer.DeepCopy())
	g.Eventually(func() []dwv2.DevWorkspace { return query("test-namespace", "updated-endpoint") }, 5*time.Second).Should(HaveLen(1))
	events.Delete(peer.DeepCopy())
	g.Eventually(func() []dwv2.DevWorkspace { return query("test-namespace", "updated-endpoint") }, 5*time.Second).Should(BeEmpty())
	require.Len(t, query("other-namespace", "test-endpoint"), 1)
}
